### ISSUE TITLE
Example data files

### ISSUE THREAD

**Issue by Indivicivet** [gjadick/fbp-recon#1]
Hi, just wondering if you have any example data files (e.g. used to generate examples/matrix.gif) or can point me to somewhere I can find them?

**Comment by gjadick** [comment]
Yes! I got the raw data to generate those images from the AAPM TrueCT Grand Challenge. I will check whether I can share that data now, otherwise the organizers will make the data public soon. 

If you have your own CT projection data, you can generate the images using the function do_recon() in fbp.py. In the "i_beta" loop, add a line to save the updated matrix at each iteration. This shows the matrix formation as data from each angle beta is added.

**Comment by gjadick** [comment]
I've checked with the AAPM challenge organizer, the Center for Virtual Imaging Trials, please reach out to them to request the data (cvit-inquire@duke.edu).

**Comment by gjadick** [comment]
I've checked with the AAPM challenge organizer, the Center for Virtual Imaging Trials, please reach out to them to request the data ([cvit-inquire@duke.edu](mailto:cvit-inquire@duke.edu)).
